language: node_js
nodejs:
    - "4.0"
branches:
    only:
        - development
before_script:
    npm install gulp -g
    gulp
script: gulp test
after_succes: cat ./reports/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
